name: Release to NuGet

on:
  release:
    types: [ published, edited ]
    
jobs:
  build-publish:

    runs-on: ubuntu-latest
    
    services:
      # Label used to access the service container
      slock:
        # Docker Hub image
        image: sujin190/slock
        #
        ports:
          # Opens tcp port 5658 on the host and service container
          - 5658:5658
        options: >-
          --health-cmd "slock-cli ping"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --logger "console;verbosity=detailed"
    - name: Pack nugets
      run: dotnet pack -c Release --no-build --include-symbols --include-source -p:SymbolPackageFormat=snupkg --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Push Symbols to NuGet
      run: dotnet nuget push "*.snupkg" --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate